INSERT INTO ACCOUNT (ID, AMOUNT_FOR_MONTH, PASSWORD, USER_NAME) VALUES (25, 2000, 'password', 'username');

INSERT INTO BUCKET (ID, ACCOUNT_ID, AMOUNT_GOAL, AMOUNT_SPENT, NAME, PERCENT) VALUES (1, 25, 200, 24.86, 'Car', 10);
INSERT INTO BUCKET (ID, ACCOUNT_ID, AMOUNT_GOAL, AMOUNT_SPENT, NAME, PERCENT) VALUES (2, 25, 400, 24.86, 'Food', 20);
INSERT INTO BUCKET (ID, ACCOUNT_ID, AMOUNT_GOAL, AMOUNT_SPENT, NAME, PERCENT) VALUES (3, 25, 600, 24.86, 'Rent', 30);
INSERT INTO BUCKET (ID, ACCOUNT_ID, AMOUNT_GOAL, AMOUNT_SPENT, NAME, PERCENT) VALUES (4, 25, 800, 24.86, 'General', 40);

INSERT INTO TRANSACTION (ID, ACCOUNT_ID, AMOUNT, BUCKET_TAG, DATE, DISPLAY_NAME) VALUES (1, 25, 15.02, 'Food', '1/4/2021', 'Groceries from Walmart');
